### PR TITLE
add dockerfile and instructions

### PR DESCRIPTION
**Pull request by shadiakiki1986**
Hey. Thanks for this repository. I added a dockerfile to server speedtest using forever. Let me know what you think

### CODE REVIEW

**Comment by shadiakiki1986** [comment]
Btw, you'll probably want to replace my username with yours in the README reference to my [automated build](https://hub.docker.com/r/shadiakiki1986/speedtest/) once you create an automated build for the dockerfile under your account

**Comment by alexte** [comment]
Thanks for your pull request. I didn't look into docker yet. 

"automatic detection of pathname": If you like to use speedtest behind some proxy with a moveable url, it would be easier to change "/blob/" to "blob/" without the prefix variable. Would this solve your issue ?

**Comment by alexte** [comment]
I tried your detection of pathname. It fails if the blob URL is "/blob/" because your code adds pathname+"/blob/", which adds up to "//blob/". And this is translated by the browser to "http://blob/"

A question about docker: Why do use "forever" inside docker ? It seems a bit redundant ? Either of them would be enough to run speedtest in background, wouldn't it ?

Do you like your docker hub URL in the README or should I register the dockerfile myself ?

**Comment by shadiakiki1986** [comment]
Hello. You're welcome.
1. automatic detection of pathname: you are right. "blob/" does indeed work. The reason I got tricked into thinking that it didn't work was in how I was using it at a different path via an nginx reverse proxy. I had a mistake in my nginx config. The mistake was
```
    location /speedtest {
        proxy_pass   http://internal:8081/;
    }
    client_max_body_size 32M;
```
which should have been
`... location /speedtest/ ...` 

Also, the url in my browser was `http://external/speedtest` (which should also have the trailing slash). Without the trailing slash, the `$.get("blob/")` was sending me to `http://external/blob` instead of `http://external/speedtest/blob`

2. using forever was just to comply with your note in the readme

3. The published dockerfile is linked to my fork of your repository. If you make any improvements to your repository, and I forget to sync my fork with yours, the published dockerfile will become outdated. I think it's better if you register your own automated build in docker hub linked to your repository instead of my fork

**Comment by alexte** [comment]
OK fine, I will change the docker hub link. Thanks..

**Pull request closed without merging**
